### ISSUE TITLE
Duplicates data in multi-page form

### ISSUE THREAD

**Issue by Ravi-kavya01** [kevinchappell/formBuilder#1000]
I am getting the last tab data for each one.

You can check this URL. It has the same issue
https://codepen.io/anon/pen/QaKrXy

Video: https://drive.google.com/file/d/1XxvHQkyRUwAEko0uXNwXszhq2ktiUIiS/view?usp=sharing

Putt the content on the last one and click save will console the data

Thanks

**Comment by Ravi-kavya01** [comment]
Can any one solve this issue?

**Comment by xaroze** [comment]
> I am getting the last tab data for each one.
> 
> You can check this URL. It has the same issue
> https://codepen.io/anon/pen/QaKrXy
> 
> Video: https://drive.google.com/file/d/1XxvHQkyRUwAEko0uXNwXszhq2ktiUIiS/view?usp=sharing
> 
> Putt the content on the last one and click save will console the data
> 
> Thanks

Is this issue solved, @Ravi-kavya01 ?

**Comment by W1-PopelierE** [comment]
@sar0z It doesn't look like this issue has been resolved yet.

**Comment by sar0z** [comment]
> @sar0z It doesn't look like this issue has been resolved yet.

Do we have any solution,  its hampering the created forms.

**Comment by PolarCoffee** [comment]
any solution yet?, having the same issue

**Comment by krebbi** [comment]
Still not resolved. 

@kevinchappell you can see the issue on your codepen https://codepen.io/kevinchappell/pen/BKYPRp when opening the console, create multiple tabs with different elements and hit "save all".
you get as many array elements as tabs but all to have the same content/elements as the last tab.

**Comment by krebbi** [comment]
I hope this helps:

https://codepen.io/krebbi/pen/VwrPjZV?editors=1111

**Comment by lucasnetau** [comment]
You need to await the promise returned by formBuilder when using multiple instances

https://formbuilder.online/docs/formBuilder/promise/

See https://github.com/kevinchappell/formBuilder/issues/1087 https://github.com/kevinchappell/formBuilder/issues/1340 https://github.com/kevinchappell/formBuilder/issues/1383
